'use client';
import {FormEvent,useEffect,useMemo,useState} from 'react';

type Severity='critical'|'high'|'medium'|'low'|'info';type Finding={id:string;category:string;title:string;status:'pass'|'warning'|'danger'|'info';severity:Severity;message:string;evidence?:string;recommendation?:string};type Port={port:number;service:string;state:'open'|'closed';protocol:'http'|'https';status?:number;latency:number};type Report={target:string;scannedAt:string;duration:number;score:number;counts:{critical:number;high:number;medium:number;low:number;passed:number};ports:Port[];findings:Finding[];limitations:string[]};
const phaseNames=['DNS kayıtları çözümleniyor','Web servis portları kontrol ediliyor','HTTP ve güvenlik başlıkları inceleniyor','Sızıntı ve yapılandırma testleri yapılıyor','Rapor hazırlanıyor'];
const severityLabel:Record<Severity,string>={critical:'Kritik',high:'Yüksek',medium:'Orta',low:'Düşük',info:'Bilgi'};

export default function Home(){
 const[target,setTarget]=useState('alperensenel.com'),[consent,setConsent]=useState(true),[loading,setLoading]=useState(false),[phase,setPhase]=useState(0),[error,setError]=useState(''),[report,setReport]=useState<Report|null>(null),[filter,setFilter]=useState<'all'|'issues'|'passed'>('all'),[section,setSection]=useState<'overview'|'ports'|'findings'>('overview');
 useEffect(()=>{if(!loading)return;const timer=setInterval(()=>setPhase(p=>Math.min(phaseNames.length-1,p+1)),1800);return()=>clearInterval(timer)},[loading]);
 const run=async(e:FormEvent)=>{e.preventDefault();if(!consent){setError('Taramayı başlatmak için yetki onayı gerekli.');return}setLoading(true);setPhase(0);setError('');setReport(null);try{const res=await fetch('/api/scan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({target,authorized:consent})});const data=await res.json() as Report&{error?:string};if(!res.ok)throw new Error(data.error||'Tarama tamamlanamadı.');setReport(data);setSection('overview')}catch(err){setError(err instanceof Error?err.message:'Tarama tamamlanamadı.')}finally{setLoading(false)}};
 const visible=useMemo(()=>report?.findings.filter(f=>filter==='all'||(filter==='issues'?(f.status==='warning'||f.status==='danger'):f.status==='pass'))||[],[report,filter]);
 const grade=report?(report.score>=90?'A':report.score>=75?'B':report.score>=60?'C':report.score>=40?'D':'F'):'—';
 const exportReport=()=>{if(!report)return;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));a.download=`webtest-${report.target}-${new Date(report.scannedAt).toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)};
 return <main><header className="topbar"><a className="brand" href="#top"><span>W</span><b>WebTest</b><small>Security Center</small></a><nav><a href="#scanner">Tarama</a><a href="#coverage">Kapsam</a><a href="https://alperensenel.com" target="_blank">Ana site ↗</a></nav><div className="status"><i/> Yetkili siteler için pasif tarama</div></header>
 {!report&&!loading&&<><section className="hero" id="top"><div className="hero-copy"><span className="kicker">PASİF & GÜVENLİ WEB DENETİMİ</span><h1>Siteni saldırgandan<br/><em>önce sen test et.</em></h1><p>Açık web servislerinden güvenlik başlıklarına kadar kapsamlı kontrolleri tek raporda gör. Sana ait veya test iznin bulunan herhangi bir herkese açık alan adını denetleyebilirsin.</p><div className="metrics"><div><b>30+</b><span>Güvenlik kontrolü</span></div><div><b>9</b><span>Web servis portu</span></div><div><b>0</b><span>Yıkıcı işlem</span></div></div></div><form className="scan-card" id="scanner" onSubmit={run}><div className="scan-head"><span className="radar">⌁</span><div><small>YENİ TARAMA</small><h2>Hedefi denetle</h2></div></div><label>Alan adı</label><div className="input-wrap"><span>https://</span><input value={target} onChange={e=>setTarget(e.target.value)} spellCheck={false} autoComplete="url"/></div><div className="allowed"><span>Kapsam</span> Herkese açık alan adları · özel ağlar hariç</div><label className="consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>Bu alan adını test etmeye yetkiliyim ve tarama kapsamını kabul ediyorum.</span></label>{error&&<p className="error">{error}</p>}<button>Güvenlik taramasını başlat <span>→</span></button><p>Parola denemesi, istismar veya veri değiştirme uygulanmaz.</p></form></section><section className="checks" id="coverage"><article><b>01</b><h3>Web servisleri</h3><p>HTTP(S) yanıtı veren yaygın uygulama ve yönetim portları.</p><span>80 · 443 · 3000 · 8080 · 8443 +</span></article><article><b>02</b><h3>Güvenlik başlıkları</h3><p>CSP, HSTS, clickjacking, MIME ve izin politikaları.</p><span>8 ayrı başlık kontrolü</span></article><article><b>03</b><h3>Sızıntı kontrolleri</h3><p>Yapılandırma dosyaları, hata sayfaları ve teknoloji izleri.</p><span>İçerik açığa çıkarmadan</span></article><article><b>04</b><h3>DNS ve e-posta</h3><p>DNSSEC, SPF, DMARC ve temel alan adı kayıtları.</p><span>Doğrulanmış DNS sorguları</span></article></section><section className="safe"><div><span>✓</span><h3>Güvenli tarama ilkeleri</h3></div><p>WebTest yalnızca kullanıcının test yetkisini onayladığı herkese açık alan adlarına düşük yoğunluklu HTTP(S) istekleri gönderir. Yerel ve özel ağ hedefleri engellenir; ham TCP taraması, güvenlik açığı istismarı, parola saldırısı, form gönderimi veya veri değişikliği yapılmaz.</p></section></>}
 {loading&&<section className="loading-view"><div className="scanner-visual"><i/><i/><i/><span>⌁</span></div><small>GÜVENLİK TARAMASI ÇALIŞIYOR</small><h2>{target}</h2><div className="phase-list">{phaseNames.map((name,i)=><div className={i<phase?'done':i===phase?'active':''} key={name}><b>{i<phase?'✓':i===phase?'●':'○'}</b><span>{name}</span></div>)}</div><p>Hedefe zarar vermeyen kontroller uygulanıyor. Bu işlem genellikle 10–25 saniye sürer.</p></section>}
 {report&&<section className="report"><div className="report-top"><div><button className="back" onClick={()=>setReport(null)}>← Yeni tarama</button><span className="kicker">GÜVENLİK RAPORU</span><h1>{report.target}</h1><p>{new Date(report.scannedAt).toLocaleString('tr-TR')} · {(report.duration/1000).toFixed(1)} saniye</p></div><div className="report-actions"><button onClick={()=>window.print()}>Yazdır</button><button onClick={exportReport}>JSON indir</button></div></div><div className="report-nav"><button className={section==='overview'?'active':''} onClick={()=>setSection('overview')}>Genel bakış</button><button className={section==='ports'?'active':''} onClick={()=>setSection('ports')}>Web servisleri <span>{report.ports.filter(p=>p.state==='open').length}</span></button><button className={section==='findings'?'active':''} onClick={()=>setSection('findings')}>Tüm bulgular <span>{report.findings.length}</span></button></div>
 {section==='overview'&&<><div className="summary-grid"><div className="score-card"><div className="score-ring" style={{'--score':`${report.score*3.6}deg`} as React.CSSProperties}><div><b>{report.score}</b><span>/100</span></div></div><div><small>GÜVENLİK PUANI</small><h2>{grade} seviyesi</h2><p>{report.score>=80?'Güçlü bir temel var; kalan maddeleri iyileştir.':report.score>=60?'Temel korumalar var ancak önemli eksikler bulunuyor.':'Öncelikli güvenlik iyileştirmeleri gerekiyor.'}</p></div></div><div className="stat critical"><b>{report.counts.critical}</b><span>Kritik</span></div><div className="stat high"><b>{report.counts.high}</b><span>Yüksek</span></div><div className="stat medium"><b>{report.counts.medium}</b><span>Orta</span></div><div className="stat passed"><b>{report.counts.passed}</b><span>Başarılı</span></div></div><div className="overview-grid"><section><div className="section-title"><h2>Öncelikli bulgular</h2><button onClick={()=>setSection('findings')}>Tümünü gör →</button></div><div className="finding-list">{report.findings.filter(f=>f.status==='danger'||f.status==='warning').slice(0,6).map(f=><FindingCard finding={f} key={f.id}/>)}{!report.findings.some(f=>f.status==='danger'||f.status==='warning')&&<div className="empty">✓ Öncelikli açık bulunmadı.</div>}</div></section><aside><h2>Servis özeti</h2>{report.ports.map(p=><div className="port-mini" key={p.port}><i className={p.state}/><b>{p.port}</b><span>{p.service}</span><small>{p.state==='open'?`Açık · HTTP ${p.status}`:'Yanıt yok'}</small></div>)}</aside></div></>}
 {section==='ports'&&<div className="table-card"><div className="section-title"><div><h2>Web servis portları</h2><p>HTTP(S) yanıtı verebilen yaygın portlar düşük yoğunlukta kontrol edildi.</p></div></div><table><thead><tr><th>Port</th><th>Servis</th><th>Protokol</th><th>Durum</th><th>Yanıt</th><th>Süre</th></tr></thead><tbody>{report.ports.map(p=><tr key={p.port}><td><code>{p.port}</code></td><td>{p.service}</td><td>{p.protocol.toUpperCase()}</td><td><span className={`port-state ${p.state}`}>{p.state==='open'?'Yanıt veriyor':'Yanıt yok'}</span></td><td>{p.status??'—'}</td><td>{p.latency} ms</td></tr>)}</tbody></table><div className="limit-note">ℹ {report.limitations[0]}</div></div>}
 {section==='findings'&&<div className="findings-page"><div className="section-title"><div><h2>Tüm güvenlik bulguları</h2><p>Her bulgu kanıt ve uygulanabilir iyileştirme önerisiyle birlikte listelenir.</p></div><div className="filters"><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>Tümü</button><button className={filter==='issues'?'active':''} onClick={()=>setFilter('issues')}>Sorunlar</button><button className={filter==='passed'?'active':''} onClick={()=>setFilter('passed')}>Başarılı</button></div></div><div className="finding-list">{visible.map(f=><FindingCard finding={f} key={f.id}/>)}</div><div className="limit-note">ℹ {report.limitations[1]}</div></div>}</section>}
 <footer><span>WebTest · Alperen Şenel</span><span>Yetkili ve pasif güvenlik denetimi</span></footer></main>}

function FindingCard({finding:f}:{finding:Finding}){const issue=f.status==='danger'||f.status==='warning';return <article className={`finding ${f.status}`}><div className="finding-icon">{f.status==='pass'?'✓':f.status==='danger'?'!':f.status==='warning'?'△':'i'}</div><div><div className="finding-meta"><span>{f.category}</span><b className={f.severity}>{severityLabel[f.severity]}</b></div><h3>{f.title}</h3><p>{f.message}</p>{f.evidence&&<code>{f.evidence}</code>}{issue&&f.recommendation&&<div className="recommend"><b>Önerilen düzeltme</b><span>{f.recommendation}</span></div>}</div></article>}
